Following Dave Robinson’s sage tweet to [write a blog post](https://twitter.com/drob/status/928447584712253440) when you've given the same advice three times, this post is a collection of my thoughts and recommendations for people interested in applying to tech jobs in the US. 

A disclaimer: I have never worked as a recruiter or career coach. This knowledge comes from mainly from studying Organizational Behavior (including negotiations and women in tech) in graduate school and my own career. These are also general principles and aren't going to fit every single situation. If there’s another tip or a caveat I should add, send me a note on twitter! 

## Application
### Online Presence 
Take stock of your online presence. Check your privacy settings on facebook or any other social media you use to make sure you've limited what's available publicly. While many online job applications now have places for twitter handles, don't include yours unless you use it mainly in a professional manner (e.g. tweeting about data science resources). 

If you have a github, pin the repos you want people to see and add READMEs that explain what the project is. I strongly recommend creating a blog to write about data science, whether it's projects you've worked on, an explanation of a machine learning method, or a summary of a conference you attended. If you need more convincing that blogging is a great use of your time, check out [this post](http://varianceexplained.org/r/start-blog/). If you program in R, you can use blogdown to create a website. [Emily Zabor](http://www.emilyzabor.com/) has written a [great tutorial](http://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html) for this; find more blogdown resources in [Mara Averick's](https://twitter.com/dataandme) [extensive list](https://maraaverick.rbind.io/2017/10/keeping-up-with-blogdown/). 

### Resume and Cover Letter
* **Keep your resume to one page**: you don’t have to list everything you’re ever done. Try making a master resume which has all of your work history and then pull what’s most relevant for each job. If you’re running out of room and have a summary or objective statement, you can leave it off as those are much less common now. If you're coming from academia, you can leave off your publications unless it's a research position in a very academic group. 
* **Proofread**: having typos in your resume can be the quickest way to have your application eliminated. Use spell-check and have a friend or two check it over. 
* **Don’t include a picture**: while this is common in some countries in Europe and South America, it is not appropriate for applying to US jobs. 
* **Tailor your resume to the position**: bigger companies often have automated resume-screening systems that check for keywords. Look in the job description to find those words; you can use a tool like [TagCrowd](https://tagcrowd.com/) to see which words are most common. For example, does it say leadership instead of management? Does it say NLP or natural language processing? Change your words to match theirs. 
* **Start your bullets with a verb**: Write "analyzed 300 papers" instead of "I analyzed 300 papers." 
* **[Quantify](https://www.themuse.com/advice/how-to-quantify-your-resume-bullets-when-you-dont-work-with-numbers) your accomplishments where possible**: instead of saying "ran experiments on our ranking algorithm", write "ran more than 60 experiments that lead to 2.3 million in additional revenue."
* **Write a cover letter**: if there is a place to submit a cover letter, do so. Some companies will eliminate candidates if they haven't written one. Just like your resume, you can have a master cover letter that you pull paragraphs from. Tailor at least the first and closing paragraph to the company and make sure you get their name correct! Try to find the hiring manager's name (see [here](https://www.themuse.com/advice/the-3-rules-of-addressing-your-cover-letter)) so you can address the letter to them instead of a "Dear Hiring Manager." If you want more guidance on writing a good letter, these articles of [31 tips](https://www.themuse.com/advice/how-to-write-a-cover-letter-31-tips-you-need-to-know) and [5 common phrases to avoid](https://www.themuse.com/advice/5-common-cover-letter-phrases-that-are-losing-you-the-job) are great places to start.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">data science hiring PSA:<br><br>some advice out there says that cover letters don&#39;t matter, so just slap a new file name on your resume and label it a cover letter, or write a single sentence that says &quot;this is my cover letter.&quot;<br><br>this is bad advice.</p>&mdash; Jesse Maegan (@kierisi) <a href="https://twitter.com/kierisi/status/993495072174899200?ref_src=twsrc%5Etfw">May 7, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

### Network
* **Use LinkedIn**: check if you know anyone at the company you're interested in. If you don't know anyone, check for second connections. If you're close with the person who bridges you, ask them if they could introduce you. 
* **Check out meetups and conferences**: sometimes hiring managers are at meetups or conferences for the express purpose of recruitment. You may also meet someone in the company or sub-industry (e.g. e-commerce) you're interested in. You can ask if they have time for an [informational interview](https://www.themuse.com/advice/3-steps-to-a-perfect-informational-interview) so you can learn more about their field. If you ask if their company has an opening or they can refer you, though, you'll probably be directed to the company's career page. This is why it's important to build your network before you need it - starting off with a strong ask is not a great way to build a mutually fulfilling relationship.

Check out my previous posts about [finding community](http://hookedondata.org/Building-Your-Data-Science-Network-Finding-Community/) and [reaching out](http://hookedondata.org/Building-Your-Data-Science-Network-Reaching-Out/) if you're interested to read more about how you can build your network. 

## Interviewing
* **Prepare and practice**: there are two main types of questions you'll be asked: technical and behavioral. For behavioral questions such as "tell me about a time you had a conflict with a team member" or "what's your greatest strength," tell a story using the situation-behavior-outcome model: describe the situation you faced, how you handled it, and what was the result. Try to keep your answers short but comprehensive. It's worth keeping a list of these examples and thinking about which ones most show case the experiences and traits most relevant to the specific job you're interviewing for. For technical questions, you'll want to find out the interview structure. Especially in new fields like data science, the structure of interviews and types of questions range widely. You may have to do a take-home, answer Computer Science questions (e.g. invert a binary tree), explain random forests, give a presentation, write SQL code, etc. It's very helpful to know ahead of time what to expect. Check out glassdoor for reviews of the interview process and ask your network if anyone's interviewed there. You can also ask HR in your initial phonescreen what to expect! If you're coming in for multiple interviews, you can ask what topics will be covered in each and what the structure will be (e.g. "Will I be doing any whiteboard coding?"). Once you know, you can focus your preparation there. 
* **Google your interviewers**: while you shouldn't stalk them, find out more about their professional accomplishments. This can be a source for your questions (see below)! For example, I was very impressed when a candidate I was interviewing asked some technical questions about a presentation I had given.
* **Anything on your resume is fair game**: If you have an internship from six years on your resume or list AWS as a skill, be prepared to be asked a question about it. 
* **Have questions ready**: each interviewer should leave time for questions at the end. If they don't, that's a bad sign! Interviewing is a two-way matching process: you're evaluating them as much as they're evaluating you. If you don't know what to ask, check out Julia Evans' [list](https://jvns.ca/blog/2013/12/30/questions-im-asking-in-interviews/). She splits them into categories such as quality of life, culture, and management practices; think about what matters most to you! You can ask each interviewer different questions to maximize how many you can get answered, but you could also try to ask multiple people the same questions to see if and how their answers differ. 
* **Never name a salary number**: don't tell them either your current salary or your expectation for this one. In some places, including New York City and California, it is actually illegal for them to ask you your current salary. If you name a number, you risk them giving you a lower offer than they would have otherwise. Their offer to you should not depend on your current salary or expectations; it should be your worth in the market and similar to the salary of your peers there! If there's question on the application form, put "NA" or "flexible;" if forced to write a number, put 0 and add somewhere else ["Note: I entered $0 on the salary question however I want to clarify I am flexible if we determine there is a mutual fit."](https://www.themuse.com/advice/answer-illegal-salary-question-right-way)  If you're asked in an interview, redirect the conversation by saying something like, "Before discussing salary, I'd like to learn more about the position and focus on what value I can bring to the company. I'm sure if it's a good fit we can reach an agreement on a competitive overall package." If it's about your current salary and you're in a different job type/industry with a lower salary, you can say something like, ["Since this position is a large change from my current job, let’s discuss what my responsibilities at this company will be and work together at the end of the process to determine a fair salary for this position."](https://biginterview.com/blog/2015/10/salary-expectations.html) If they insist on knowing your expectation, give a large range based on research into what's standard in the industry and at that company. For example, you can say, "From my research and past experience, my understanding is a base salary of $95k to $120k is standard, but I'm most interested in the fit with the position and overall compesnation package." You can look at the [H1B visa data](http://h1bdata.info/index.php), [Glassdoor](https://www.glassdoor.com/), and [paysa](https://www.paysa.com/salaries/) to give yourself a ballpark. And talk to friends! Knowledge is power. Some friendly folks will also do a salary information exchange: 

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">while I&#39;m on it, my DMs are always open if you want to send me your salary. especially if you work in data, work in Toronto, or work in a &quot;technical&quot; role with 0-3 years of experience. if you&#39;re an URM, I&#39;ll tell you mine too. knowledge is power 💪</p>&mdash; Sharla Gelfand (@sharlagelfand) <a href="https://twitter.com/sharlagelfand/status/985599731601723393?ref_src=twsrc%5Etfw">April 15, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## Offer stage
### Initial response
For the initial offer, you may get a phone call, an email with the details, or an email asking for time to go over the offer by phone. In all cases, make sure you express your excitement and gratitude for the opportunity. Don't accept right away; get the full offer in writing, say you need to review the offer, and ask if you can can reconnect in a few days. This sets the stage for negotiating and gives you time if you're considering other offers. If you need more information (e.g. starting date possibilities, health insurance information), you should ask for it before your second conversation so you can have the full picture. 

### Juggling multiple options

Unfortunately, you probably won't get offers (or rejections) from all the companies you're interested in at once. More likely, when you get an offer, you might be in the final round for another company, just finished the phone screen in another, and waiting to hear back from others. What if one of the ones you're waiting on is your "dream job"? 

If you're in or very close to the final round with a company, tell them about your other option. Reiterate how interested you are in their company (and if they're your first choice, tell them!), but explain that you're received another offer and would appreciate if they would be able to give you a decision by X date. Recruiters understand that you're likely to be interviewing with other companies and deal with this situation all the time! If you're very early in the other process, it's unlikely they'll be able to speed it along enough to have an offer in time. 

### Negotiate

Even if the offer is more than you expected or it would be a big increase from your current job, you should negotiate. Tech companies **expect** you to negotiate. You can almost always get at least another $5k or a 5% increase in base salary and very likely more depending on the company and original offer. Or you could ask for a signing bonus or more stock options.  Remember that it's not selfish or greedy to negotiate:

<blockquote class="twitter-tweet" data-conversation="none" data-lang="en"><p lang="en" dir="ltr">Other thoughts: it&#39;s not about the salary you make now. It&#39;s about the salaries of your peers at the new place. It may be a large bump for you now, but once you&#39;re hired you&#39;ll be doing the same work for less pay.</p>&mdash; bletchley punk (@alicegoldfuss) <a href="https://twitter.com/alicegoldfuss/status/991829556267958272?ref_src=twsrc%5Etfw">May 2, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

You can also negotiate for non-monetary benefits. For example, maybe you want to be able to work from home one day a week. Maybe you want them to cover the cost of two conferences a year. If it's a smaller company, you can ask for a different job title. 

How much you can negotiate for depends on your bargaining position and the company. A non-profit will probably have less room on salary. If you have another offer or you're well compensated in your current job, you have a strong alternative. If you have a rare skill that they recruited you for, it's going to be harder for them to find someone else. You should do your research on the salary websites mentioned above so you can explain why you're asking for the numbers you are. Aim high so you have room to compromise and give a number, not a range - if you say you're looking for between a 5k and 10k increase, they'll probably give you the 5k. Finally, start the conversation with the set of things you're interested in instead of raising and settling one issue after another. This way, they'll both feel they have the picture of what you want and you can do compromises among issues (e.g. you might accept a $5k base salary increase and $5k signing bonus instead of a $10k base salary increase). 

There are great resources online to learn more about how to negotiate well; this HBR article with [15 rules for negotiating an offer](https://hbr.org/2014/04/15-rules-for-negotiating-a-job-offer) and this one with [advice for women] (https://hbr.org/2014/06/why-women-dont-negotiate-their-job-offers) (who unfortunately need to adopt different negotiation tactics) are good places to start. 

It is *very*, *very*, *very* rare for a company to pull an offer because you negotiated. If they do, you do not want to work there. 

One caveat: if you're negotiating and you get everything you ask for, the company expects you to accept! You of course don't have to, but you shouldn't be stringing along a company you're not serious about. And knowing you'll accept also allows you to say the magic words, "If you can do X, Y, and Z, I would be thrilled to accept the offer." 

## Leaving your job
* **Tell your manager first**: your manager needs to be the first person to tell. Unless it was a toxic work environment, emphasize how much you're learned and enjoyed working there and how this new job offers something your current one couldn't (e.g. experience at a small startup vs. a multinational corporation). Hopefully, they'll understand and be excited for you. They may also make a counter-offer by offering a bonus or change in your responsibilities to get you to stay. There's different views on whether you should accept this counter-offer; on the one hand, outside offers give you one of the strongest negotiating positions for receiving a raise, but on the other hand, they may signal to your manager you're not committed to your job (research has found this especially true [for women](https://hbr.org/2014/06/why-women-dont-negotiate-their-job-offers)). If you're nervous about the conversation, check out [this article](https://www.themuse.com/advice/the-almost-painfree-guide-to-having-the-i-quit-conversation-with-your-boss) for more guidance. 
* **Meet with your closest colleagues one-on-one**: if you've worked extensively with someone, they'll probably appreciate you telling them in person instead of finding about by email. For example, when I left Etsy, I met individually with the other two search analysts and the search engineering partners. This is also a nice way to set a basis for continuing your friendship after you leave. 
* **Make a to-do list and share with your manager**: create a list of current projects and figure out which ones you can wrap up and which ones you'll have to pass on. Work with your manager to figure out who can take on which project and what you should do to make the handoff easiest. Having it on a shared google document lets them check everything is on track without having to ping you. 

## Conclusion
Job hunting is stressful, especially if you're working full-time and/or looking to change industries. I hope this post has given you a good starting point for understanding the hiring process in data science, what mistakes to avoid, and what strategies you can leverage in the process. As I said at the start, feedback and additions to this post are very welcome!
