Following Dave Robinson’s sage advice to write a blog post when you find yourself giving the same advice three times, I’ve written this post to collect my thoughts and recommendations for people interested in apply to tech jobs in the US. 

A disclaimer: this knowledge comes from leadership courses in college, studying Organizational Behavior (including negotiations and women in tech) in graduate school, and my own career. I have not worked as a recruiter or career coach and don’t claim to know everything; if you think there’s something another tip or a caveat I should add, send me a note on twitter!

## Application

* Clean up social media profiles. Check your privacy settings on facebook or any other social media you use to make sure . While many online job applications now have places for twitter handles, don't include yours unless you use it mainly in a professional manner (e.g. tweeting about data science resources). 

### Resume
* Keep your resume to one page. You don’t have to list everything you’re ever done. Try making a master resume which has all of your work history and then pull what’s most relevant for each job. If you’re running out of room and have a summary or objective statement, you should leave those off, as those are much less common now. If you're coming from academia, you can leave off your publications unless it's a research position in a very academic group. 
* Don’t include a picture. While this is common in some countries in Europe, it is not appropriate for applying to US jobs. 
* Tailor your resume to the position. Bigger companies are likely to have automated systems checking for keywords to help them screen out resumes. Look in the job description to find those words. For example, do they say leadership instead of management? Do they say NLP or natural language processing? Change your words to match theirs. 

### Network
 
## Interviewing: 
* Don’t name a salary number. (give some guidance for that). To give yourself a ballpark, can look at the H1BC data, Glassdoor, and payscale. And talk to friends! Knowledge is power. 
* Google your interviewers to find out more about their professional accomplishments. I was impressed impressed when someone referenced a presentation I had given 
* Have questions ready. Examples: 
    * Julia Evans has one: https://jvns.ca/blog/2013/12/30/questions-im-asking-in-interviews/. 
    * That twitter list for startup questions

## Offer stage
* Negotiate: Always negotiate. Even if the offer is more than you expected or it would be a big increase from your current job. Tech companies *expect* you to negotiate. You can almost always get at least another $5k or a 5% increase. It's not selfish to negotiate for more salary. You can also probably get more stock options (see below) and a signing bonus.  

But you can also negotiate for other things depending on your priorities. For example, maybe you want to be able to work from home one day a week. Maybe you want them to cover the cost of two conferences a year. If it's a smaller company, you can ask for a different job title. 

It is *very*, *very*, *very* rare for a company to pull an offer because you negotiated if you did so professionally.

* RSUs vs stock options. Most tech companies will offer you some form of stock depending on their size. These will generally vest over a four year period with a one year cliff. In english, that means that you will get your first options after a year. After that, you'll get more every three months. For example, at Etsy I recieved X dollars of Restricted Stock Units (RSUs) vesting over four years. Because Etsy's stock price more than doubled since I started there (from $12 to $28), XYZ. When you leave a company, you get to keep all the stock you're earned up to that point. 

If the company isn't public, you'll generally get options to buy the stock at a certain price. This price, known as the strike price, will be in your contract. Options at a private company are a bit like a lottery ticket - if your company turns into another Google/Amazon/Facebook, they could be worth hundreds of thousands of dollar if you were a very early employee. On the other hand, if your company goes public but the stock never goes above your strike price, they're worthless. And if you leave a company before it's sold or goes public, you'll either have to buy your options or give them up. 

